### ISSUE TITLE
[Suggestion] Set default checkpoint path in params

### ISSUE THREAD

**Issue by Colanim** [xcfcode/seq2seq-summarizer#1]
After training with default parameters (`python train.py`), I tried to test with default parameters too :

`python test.py`

But it give me the error :

> Load train_status from:None
> Traceback (most recent call last):
  File "test.py", line 213, in <module>
    train_status = torch.load(args.model)
> AttributeError: 'NoneType' object has no attribute 'seek'. You can only torch.load from a file that is seekable. Please pre-load the data into
a buffer like io.BytesIO and try to load from it instead.

If I understood well, it's because I didn't give a path for checkpoints.

I could fix the error by calling :

`python test.py --model checkpoints/rouge-bahdanau/cnndm.train.pt`

---

I suggest setting a default parameter for the checkpoint in `params.py`.

**Comment by xcfcode** [comment]
You are right, the original code just uses the checkpoint dir to save all the results, I changed it into this format which can create a secondary dir to make sure of every experiment. But I forget to change codes in the test.py. Thanks a lot.
